# Generated by Django 5.2.10 on 2026-01-19 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_historicalpost_options_alter_post_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpost',
            name='image',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
    ]
